[tool.poetry]
name = "slack-profile-update"
version = "0.1.0"
description = ""
authors = ["cob16 <public+github@cormacbrady.info>"]

[tool.poetry.dependencies]
python = "^3.7"
slackclient = "^2.8.1"
black = "^20.8b1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-recording = "^0.9.0"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
