version: 2.1

executors:
  python:
    description: CircleCI python image that includes poetry
    docker:
    - image: cimg/python:3.8.0
    - image: cimg/postgres:14.4
      environment:
        POSTGRES_USER: postgres
    environment:
      POETRY_CACHE_DIR: /home/circleci/project/.poetry
    parameters:
      tag:
        default: latest
        type: string

jobs:
 test:
  executor: python
  steps:
    - setup_remote_docker
    - checkout
    - run:
        name: update package index
        command: sudo apt update
    - run:
        name: install postgress client
        command: sudo apt install -y postgresql-client
    - run:
        name: setup db
        command: psql -a -f tools/create_postgres_db.sql
    - restore_cache:
        keys:
          - 'deps-{{ checksum "poetry.lock" }}'
    - run:
        name: Poetry - install
        command: poetry install
    - save_cache:
        key: 'deps-{{ checksum "poetry.lock" }}'
        paths:
          - /home/circleci/project/.poetry/virtualenvs
    - run:
        name: run tests
        command: poetry run pytest

workflows:
  main:
    jobs:
      - test
